query=
PREFIX rdf:<http://www.w3.org/1999/02/22-rdf-syntax-ns#> 
PREFIX rdfs:<http://www.w3.org/2000/01/rdf-schema#>
PREFIX core:<http://vivoweb.org/ontology/core#>
SELECT
    ?uri ?label
 WHERE {
    ?uri a core:InformationResource .
    ?uri rdfs:label ?label .
    FILTER regex(?label, "This is the Title of our test publication", "i") . 
}
LIMIT 10
