query=
PREFIX rdf:<http://www.w3.org/1999/02/22-rdf-syntax-ns#> 
PREFIX rdfs:<http://www.w3.org/2000/01/rdf-schema#>
PREFIX core:<http://vivoweb.org/ontology/core#>
PREFIX bibo:<http://purl.org/ontology/bibo/>
SELECT
    ?uri ?label 
WHERE
{
    ?uri a bibo:Journal .
    ?uri rdfs:label ?label .
    FILTER regex(?label, "International Journal of Testing", "i")
}
LIMIT 10
